// EAViewEngine.idl : IDL source for EAViewEngine
//

// This file will be processed by the MIDL tool to
// produce the type library (EAViewEngine.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	uuid(E537DA4A-9A1F-4DB8-8174-DD5E69A8F4D7),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{E9B17698-FA7F-4316-B3B1-24F714F7A7B2}")
]
library EAViewEngineLib
{
	importlib("stdole2.tlb");
	[
		uuid(E9B17698-FA7F-4316-B3B1-24F714F7A7B2)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
};

